[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "langgraph-powerbi-agent"
version = "0.0.1"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["app"]

